### ISSUE TITLE
Implementasi User Management & Role Management yg terscope berdasarkan conference. 

### ISSUE THREAD

**Issue by rahmanramsi** [OpenSynergic/leconfe#218]
Saat ini list user yang ditampilkan adalah semua user yang terdaftar kedalam aplikasi. Tidak terscope berdasarkan conferencenya.

## Todo

- [ ] Scope user berdasarkan conference
- [ ] Scope role berdasarkan conference
- [ ] Ketika conference baru dibuat, maka role untuk conference tersebut otomatis akan dibuat juga
- [ ] User Role juga akan terscope ke conference. Hal ini akan membuat perbedaan role tiap user di setiap conferencenya.
- [ ] Implementasi hak akses otomatis harus juga berdasarkan role user yang ada di conference tersebut. Contohnya ketika `User A` mengakses `Conference A` dan role `User A` adalah `Editor` maka `User A` dapat melakukan hal" yang bisa dilakukan oleh role `Editor`. Namun ketika `User A` mengakses `Conference B` dan role `User A` adalah `Author` maka `User A` hanya dapat melakukan hal" yang bisa dilakukan oleh role `Author` di `Conference B`. Jadi untuk setiap conference, hak akses user tersebut bisa berbeda-beda tergantung role yang ada diconference tersebut.
- [ ] Disaat register, ketika register dihalaman spesifik conference, maka akan terdaftar ke conference tersebut. Dan jika register dihalaman utama (halaman institusi) maka akan ada pilihan untuk mendaftar di conference mana saja. Contohnya seperti implementasi dari OJS
- [ ] Disaat login ke conference yang user tersebut tidak terdaftar maka akan diarahkan ke halaman profile. Disitu user dapat mendaftar jadi user dan memilih role yang ada di conference tersebut.
